#!/usr/bin/env node

/*!
 * hs-client@0.0.9 build
 * Bundled by bpkg on 2020-08-17T14:23:04.901Z
 */

'use strict';

var cp = require('child_process');
var fs = require('fs');
var path = require('path');
var env = process.env;
var basename = path.basename;
var dirname = path.dirname;
var extname = path.extname;
var join = path.join;
var normalize = path.normalize;
var resolve = path.resolve;

var PREFIX = process.platform === 'win32'
  ? resolve(process.execPath, '..')
  : resolve(process.execPath, '..', '..');

var NAME = 'hs-client';
var VERSION = '0.0.9';
var PKG = join(NAME, 'package.json');
var CWD = __dirname;

var MODULES = [];

var LINKS = [
  [
    "bin",
    "$NODE_MODULES/hs-client/bin/hsd-cli",
    "$BIN/hsd-cli"
  ],
  [
    "bin",
    "$NODE_MODULES/hs-client/bin/hsd-rpc",
    "$BIN/hsd-rpc"
  ],
  [
    "bin",
    "$NODE_MODULES/hs-client/bin/hsw-cli",
    "$BIN/hsw-cli"
  ],
  [
    "bin",
    "$NODE_MODULES/hs-client/bin/hsw-rpc",
    "$BIN/hsw-rpc"
  ],
  [
    "license",
    "$NODE_MODULES/hs-client/LICENSE",
    "$LICENSES/hs-client/LICENSE"
  ]
];

var ENGINE = 524288;
var ENCODED = '8.0.0';

function parseArgs() {
  var options = {
    shell: true
  };

  var args = getArgs(process.argv);

  for (var i = 2; i < args.length; i++) {
    var arg = args[i];
    var next = '';

    if (i + 1 < args.length)
      next = args[i + 1];

    switch (arg) {
      case '-h':
      case '--help': {
        console.log('');
        console.log('  Usage: ./build [options]');
        console.log('');
        console.log('  Options:');
        console.log('');
        console.log('    -s, --shell <path>  path to shell');
        console.log('    -h, --help          output usage information');
        console.log('');
        process.exit(0);
        break;
      }

      case '-s':
      case '--shell': {
        if (!next || next[0] === '-')
          throw new Error('Invalid option for: ' + arg + '.');

        options.shell = next;
        i += 1;

        break;
      }

      default: {
        throw new Error('Invalid argument: ' + arg + '.');
      }
    }
  }

  return options;
}

function main() {
  var options;

  try {
    options = parseArgs();
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }

  process.chdir(CWD);

  if (!fs.existsSync(PKG)) {
    console.error('Error: wrong directory for %s install!', NAME);
    process.exit(1);
  }

  console.log('Building %s@%s...', NAME, VERSION);
  console.log('');

  var parts = process.version.split(/[^\d]/);
  var version = (0
    + (parts[1] & 0xff) * 0x10000
    + (parts[2] & 0xff) * 0x00100
    + (parts[3] & 0xff) * 0x00001);

  if (version < ENGINE) {
    console.error('Error: %s requires node@%s!', NAME, ENCODED);
    process.exit(1);
  }

  for (var i = 0; i < MODULES.length; i++) {
    var mod = MODULES[i];
    var name = mod[0];
    var dir = mod[1];
    var install = mod[2];
    var optional = mod[3];

    console.log('Building "%s"...', name);
    console.log('');

    try {
      cp.execSync(install, {
        cwd: resolve(CWD, dir),
        stdio: 'inherit',
        shell: options.shell
      });
    } catch (e) {
      if (!optional) {
        console.error(e.message);
        process.exit(1);
      }

      console.log('Warning: build failed for optional dependency "%s"!', name);
      console.log('');

      continue;
    }

    console.log('');
  }

  console.log('%s@%s successfully built!', NAME, VERSION);
  console.log('');
  console.log('If you are an OS package maintainer, you may now');
  console.log('package the "%s" directory in its entirety.', NAME);
  console.log('Note that node.js packages typically reside in:');
  console.log('');

  if (process.platform === 'win32') {
    // Global paths:
    console.log('  - %PROGRAMFILES\\lib\\node');
    console.log('  - %PROGRAMFILES(X86)\\lib\\node');
    // NPM install paths:
    console.log('  - %APPDATA\\npm\\node_modules');
    console.log('');
    console.log('Current system paths:');
    console.log('');
    console.log('  - %s', resolve(PREFIX, 'lib', 'node'));
    if (env.APPDATA)
      console.log('  - %s', resolve(env.APPDATA, 'npm', 'node_modules'));
  } else {
    // Global paths:
    console.log('  - $PREFIX/lib/node');
    // NPM install paths:
    console.log('  - $PREFIX/lib/node_modules');
    console.log('');
    console.log('Current system paths:');
    console.log('');
    console.log('  - %s', resolve(PREFIX, 'lib', 'node'));
    console.log('  - %s', resolve(PREFIX, 'lib', 'node_modules'));
  }

  if (LINKS.length > 0) {
    console.log('');
    console.log('Here are some necessary symlinks:');
    console.log('');

    for (var j = 0; j < LINKS.length; j++) {
      var link = LINKS[j];
      var from = normalize(link[1]);
      var to = normalize(link[2]);

      console.log('  %s -> %s', to, from);
    }
  }

  console.log('');

  process.exit(0);
}

function getArgs(argv) {
  if (!argv || typeof argv.length !== 'number')
    throw new TypeError('"argv" must be an array.');

  var args = [];

  for (var i = 0; i < argv.length; i++) {
    var arg = argv[i];

    if (typeof arg !== 'string')
      throw new TypeError('"arg" must be a string.');

    if (arg.startsWith('--')) {
      // e.g. --opt
      var index = arg.indexOf('=');
      if (index !== -1) {
        // e.g. --opt=val
        args.push(arg.substring(0, index));
        args.push(arg.substring(index + 1));
      } else {
        args.push(arg);
      }
    } else if (arg.startsWith('-')) {
      if (arg.length > 2) {
        // e.g. -abc
        for (var j = 1; j < arg.length; j++)
          args.push(`-${arg.charAt(j)}`);
      } else {
        // e.g. -a
        args.push(arg);
      }
    } else {
      // e.g. foo
      args.push(arg);
    }
  }

  return args;
}

main();
